name: berry-bot
channels:
  - defaults
  - conda-forge
  - robostack
dependencies:
  - python
  - sphinx-book-theme
  - pip
  - jupyter-book
  - ipykernel
  - numpy
  - matplotlib
  - sphinx-thebe
  - ros-noetic-desktop
  - catkin_tools
  - jupyterlab
  - jupyter-ros