name: berry-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sphinx-book-theme
  - pip
  - jupyter-book
  - ipykernel
  - numpy
  - matplotlib
  - sphinx_thebe
  - pip:
    - furo